### ISSUE TITLE
universe filterAll method missing

### ISSUE THREAD

**Issue by Hypercubed** [crossfilter/universe#19]
The documentation shows usage of a `filterAll` method on a universe instance (https://github.com/crossfilter/universe#explore-your-data).  However this method, while it exists in the `./src/filters.js` file (https://github.com/crossfilter/universe/blob/master/src/filters.js#L48) ), is not exposed on the universe instance.  Furthermore, the `filterAll` method as it exists is not sufficient.

Here is a gist of a mocha tests for filterAll: https://gist.github.com/Hypercubed/fb7eac133e8675f3e193de36cd3d3459

You will see three tests:

1) filterAll method is not exposed
2) filterAll method clears the universe.filters object but does not clear the individual filters.
3) A promise chain that does clear each filter and clears the filter object.

Given this I think the proper filterAll method should be:

```
function filterAll() {
  return Promise.all(_.keys(service.filters).map(function(key) {  // clearing each filter
    return service.filter(key)
  }))
  .then(function() {  // clearing filters object
    return applyFilters({})
  })
}
```

or equivalent.

**Comment by tannerlinsley** [comment]
Submit a PR + docs and we will get it merged

**Comment by Hypercubed** [comment]
Will do, just want to make sure I understand the intent.

**Comment by tannerlinsley** [comment]
Ah I see what you're saying now. It isn't intended for that use. See here
https://github.com/crossfilter/universe/blob/master/src/filters.js#L12 it
is exposed. Its purpose is to clear all filters. Its method name is the
same as that of the same method in cross filter.

**Comment by Hypercubed** [comment]
Yes, I can confirm.  if you look at the mocha test #2 in the gist (https://gist.github.com/Hypercubed/fb7eac133e8675f3e193de36cd3d3459#file-filterall-js-L38) line 70 passes (the filter object is empty), but line 74 fails because the filter is still in place on the dimension.

So I can replace `filterAll` with a promise chain like this:  https://gist.github.com/Hypercubed/fb7eac133e8675f3e193de36cd3d3459#file-filterall-js-L113 but that doen't solve the issue that `applyFilters` doesn't clear existing filters that are not in `newFilters`.  Since `filter` clones existing filters the only place I see this can come up is `filterAll` when it calls `applyFilters({})`.

I have other issues with `applyFilters` that I need to isolate as well.
