### ISSUE TITLE
Bugs in filter method

### ISSUE THREAD

**Issue by Hypercubed** [crossfilter/universe#20]
I haven't had the time to isolate this one into a test but if I create a filter using a function:

```
const fn => () { /* some function /* }
universe.filter('search', fn)
```

Then later try to add another filter I get the error: `f is not a function at filterIndexFunction`.

I have determined this is because the filter function gets converted to a string here:  https://github.com/crossfilter/universe/blob/master/src/filters.js#L38

My suggested solution is:

```
      var newFilters = _.clone(service.filters, true)
      _.map(newFilters, function(fil, i) {
        if (fil.type === 'function') {
          fil.function = service.filters[i].function
          fil.value = service.filters[i].value
        }
      })
```

**Comment by tannerlinsley** [comment]
Could you reproduce it in a js fiddle perhaps?

**Comment by Hypercubed** [comment]
Sure... here is an example of the error on requirebin: 
http://requirebin.com/?gist=f8776df2fcc6454312112640146e1455

**Comment by Hypercubed** [comment]
I have finally isolated what I think is a second bug in the `.filter` method.  Please see here:  http://requirebin.com/?gist=c46905817eea9f13c12d08dbf6554ce3 

The toggle mechanism (here https://github.com/crossfilter/universe/blob/master/src/filters.js#L106) allows us to toggle a single value of an `inclusive` filter on and off.  However, because of the `clone` (discussed above) adding a new independent filter causes other filters to be toggled off.

I think these two bugs (if someone can confirm they are in fact bugs and not my misunderstanding) are indicating that we should revisit the filter method.  I'm not sure what the reasoning behind using `applyFilters` and mapping over all filters when each filter is added.  Shouldn't we instead have singular `applyFilter` method that adds a new filter and leaves the others untouched?

**Comment by Hypercubed** [comment]
I combine these two bug reports into one issue because I think the solution might be coupled.

**Comment by tannerlinsley** [comment]
I think you get the idea now.  That looks like a bug to me.  For backstory, the `applyFilters` method is there for serialization in and out of filters.  It is common to want to save your filter state for later.  

Other than that, the toggle filter function is exactly how you've imagined it.  When a toggle becomes a single value, it get's transformed into an `exact` filter so crossfilter can be more performant.  

If it's getting erased when filtering on another value, I'm pretty surprised.  I was using Universe in production myself for a few weeks and never saw that bug. 

Let's get the tests to a thorough state, and if it's still happening on the lastest build, you should definitely refactor the filtering to make those use cases pass.

**Comment by Hypercubed** [comment]
I'll do a PR (soon) for the AVA tests.  Then in a separate PR I will add two failing tests for these bugs.

**Comment by Hypercubed** [comment]
I've been bypassing the toggle by using `replace` which doesn't do the toggle.

Here I have added two failing tests that demonstrate these issues:

https://github.com/Hypercubed/universe/blob/demo/issue20/test/filter.spec.js#L125
https://github.com/Hypercubed/universe/blob/demo/issue20/test/filter.spec.js#L287

**Comment by Hypercubed** [comment]
Ok, maybe a solution.  Instead of a deep clone we do a shallow copy.  Then ignore all filters that are strictly equal to previous.  Only two lines change and passes all tests.

https://github.com/Hypercubed/universe/blob/fix/filters/src/filters.js

**Comment by Hypercubed** [comment]
If you have a chance to look I modified lines https://github.com/Hypercubed/universe/blob/fix/filters/src/filters.js#L38 and https://github.com/Hypercubed/universe/blob/fix/filters/src/filters.js#L93 .  If you want to stick with the lodash approach should probably change Object.assign to the lodash equivalent.
