### ISSUE TITLE
Add a linter?

### ISSUE THREAD

**Issue by Hypercubed** [crossfilter/universe#21]
I've noticed that the code contains mixed styles (ASI and semicolons).  Would you consider a PR to add a linter?  I prefer XO.  Standard and semi-standard are both good as well.  Personally, I prefer semicolons and spaces... but I will set up the linter however you prefer.

**Comment by tannerlinsley** [comment]
Sure thing. I would prefer 2 space indentation and no unnecessary semi
colons. What do you think?

**Comment by Hypercubed** [comment]
I prefer punctuation.  But I wouldn't fight about it... twitch.  I'll setup xo with those settings.

The reason why I'm suggesting it is to enforce the rules on myself.

**Comment by tannerlinsley** [comment]
Try no punctuation this time around. I switched a couple months ago and
have loved it since. ;)

**Comment by Hypercubed** [comment]
Close in #23
