### ISSUE TITLE
Root universe.js and universe.min.js

### ISSUE THREAD

**Issue by Hypercubed** [crossfilter/universe#24]
Currently, you are using gulp and browserify to build `universe.js` and `universe.min.js` files in the root.  `package.json` uses `src/universe.js` as main.  The tests use `'../universe.js'` (the browserified version).  Can I suggest that the tests use `src/universe.js` and we .gitignore the built files?  Are you planning to support bower?

Also, as an aside, I mostly switched from using gulp to using only [npm scripts](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/).  Since this build is fairly simple we might consider the same here.

**Comment by tannerlinsley** [comment]
Love npm scripts. Check out PS by kentcdodds

**Comment by Hypercubed** [comment]
Yes, P-S is great.  So you think we can add universe.js and universe.min.js to .gitignore.  I think the only reason not to is to support bower.

**Comment by tannerlinsley** [comment]
I'm more than okay not supporting bower.  It's dead to me anyway haha

**Comment by Hypercubed** [comment]
Took care of this in #31
