### ISSUE TITLE
Codepen example is broken

### ISSUE THREAD

**Issue by zsherman** [crossfilter/universe#33]
On chrome v51 http://codepen.io/tannerlinsley/pen/oxjyvg?editors=0010

**Comment by tannerlinsley** [comment]
@Hypercubed did we change anything that could have affected this?

**Comment by zsherman** [comment]
@tannerlinsley looks like it's just having trouble fetching `universe.min.js`

**Comment by tannerlinsley** [comment]
Fixed. Its now pointing at the cdn

**Comment by salzig** [comment]
@tannerlinsley "same" problem again.
