### ISSUE TITLE
crossfilter2 package.json error when compiling

### ISSUE THREAD

**Issue by rodryquintero** [crossfilter/universe#40]
I got this error after installing it. Using it with Webpack and Babel. I don't know if it helps but I was using Crossfilter.js without issues.

![image](https://cloud.githubusercontent.com/assets/1271370/20714979/b1912ab0-b61b-11e6-89ed-f360c4b87afc.png)

Let me know if you need more information.

**Comment by esjewett** [comment]
Take a look at this issue: https://github.com/crossfilter/crossfilter/issues/62

I think it's the same problem :)

**Comment by rodryquintero** [comment]
Thanks for the quick reply. I will look into it! :+1:

**Comment by rodryquintero** [comment]
Installed the Json loader and it worked. Thanks.
