### ISSUE TITLE
New tag version

### ISSUE THREAD

**Issue by tonyper** [crossfilter/universe#42]
Could we have a new tag version including the latest code from master ?

I'd personally need that to be able to integrate the latest fix into bower

**Comment by tannerlinsley** [comment]
I've pushed a tag for you :)

**Comment by tonyper** [comment]
Thanks a lot, I should have specified though that I need to have access to universe.min.js from that tag
Could you please add this file ?

**Comment by tannerlinsley** [comment]
The tags don't include the built files. Though you can access them by
installing via npm or via npmcdn.com/universe@latest/universe.min.js

**Comment by tonyper** [comment]
Great, I didn't know about npmcdn
Thanks a lot !

**Comment by tannerlinsley** [comment]
You bet 😊
