### ISSUE TITLE
Track and manage queries (groups)

### ISSUE THREAD

**Issue by tannerlinsley** [crossfilter/universe#6]
Right now, dimensions are tracked and managed with easy references in `universe.columns`, but the queries made on those columns are not tracked anywhere.  

`universe.columns[n].queries` would be a great place to put these query objects.  

We could store there:
- the original query object
- crossfilter group
- listeners/callbacks
- post-aggregations (in the future)
- etc.

**Comment by etimberg** [comment]
@tannerlinsley some questions.

1. what gets stored in the crossfilterGroup property? 
2. What is the original query object?

**Comment by tannerlinsley** [comment]
Let me remember how it's roughly structured first:

Universe
- cf (crossfilter instance)
- columns []
  - column {}
    - key
    - type
    - dimension (crossfilter)
    - listeners
    - etc...
    - queries []?

Okay, so right now that query array doesn't exist, but the queries do.  They get returned here: https://github.com/crossfilter/universe/blob/master/src/query.js#L81 

I'm not sure if that would be the correct place to track all of them, but I would start there, since each query is dependent on the column and its dimension.

Re: first question
I would think that it would most likely be what is currently being returned at https://github.com/crossfilter/universe/blob/master/src/query.js#L81 , plus some extra stuff:

- queries []
  - query {}
    - originalQueryObject {} (currently not there)
    - crossfilter instance (exists)
    - crossfilter dimension instance (exists)
    - crossfilter group instance (exists)
    - universe instance (exists)
    - listeners ? ...
    - post aggregation api ? ...

Re: second question
original query object === `myQuery` below:

```javascript
var myQuery = {groupBy: 'tag', select: {...}}
universe.query(myQuery)


I feel like this is scattered, let me know if I'm not being ver clear ;)
